### ISSUE TITLE
Web App Builder / NodeJS version requirement?

### ISSUE THREAD

**Issue by DemersM** [Esri/generator-esri-appbuilder-js#148]
Hi, 

First time trying this generator with WAB v2.9 and NodeJS v6.9.1.

I have an error when using `yo esri-appbuilder-js` after installing grunt, yo, and generator-esri-appbuilder-js

```
module.exports = async options => {
                       ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ville_service\AppData\Roaming\npm\node_modules\generator-esri-appbuilder-js\node_modules\yeoman-generato
r\lib\index.js:9:19)
    at Module._compile (module.js:570:32)
```

I suspect the error is with the NodeJS 6.9.1 version not being compatible. Is is right? 

What are the required versions for NodeJS and WAB?

**Comment by gavinr** [comment]
[As of v4.0.0, node v6 is not supported ](https://github.com/Esri/generator-esri-appbuilder-js/releases/tag/v4.0.0)- I'm not sure what is the current lowest supported version but recomended would be current LTS Nodejs version. 

There's a note on the nodejs versions we're testing [here](https://github.com/Esri/generator-esri-appbuilder-js/blob/master/.travis.yml), but I think we should probably make that more explicit (maybe a section in the readme?) Sorry for the lack of explanation.

**Comment by DemersM** [comment]
Thank you for the info!

**Comment by gavinr** [comment]
added a note in 7ffa7f8c31a1e86509438b3695c5716d58f20208
