### ISSUE TITLE
NPM run build error - bower is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by ryan-WORK** [Esri/generator-esri-appbuilder-js#171]
When building out the widget everything looked like it was working correctly. When I went to run the build command I got the following error. 

```
~/Desktop/arcgis-web-appbuilder-2.20/ArcGISWebAppBuilder/widget-developemnt $ npm run build
> widget-developemnt@1.0.0 build C:\Users\user\Desktop\arcgis-web-appbuilder-2.20\ArcGISWebAppBuilder\widget-developemnt
> esri-wab-build C:/Users/user/Desktop/arcgis-web-appbuilder-2.20/ArcGISWebAppBuilder/server/apps/6
Cleaning dist directory...
########## BUILD START TIME: Tue Jun 22 2021 17:39:33 GMT-0700 (Pacific Daylight Time) ##########
'bower' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:679
    throw err;
    ^
Error: Command failed: bower install esri=arcgis-js-api#3.36 dgauges=https://github.com/dmandrioli/dgauges.git#383a47f2216be432d866d1add0a95ce40f62da52 dijit-themes=https://github.com/dojo/dijit-themes.git#1.14.0 --force-latest  --config.directory=.
    at checkExecSyncError (child_process.js:640:11)
    at execSync (child_process.js:676:15)
    at Object.exports.build (C:\Users\userl\Desktop\arcgis-web-appbuilder-2.20\ArcGISWebAppBuilder\widget-developemnt\node_modules\esri-wab-build\app\buildTool.js:68:3)
    at Object.exports.buildApp (C:\Users\user\Desktop\arcgis-web-appbuilder-2.20\ArcGISWebAppBuilder\widget-developemnt\node_modules\esri-wab-build\app\remoteBuild.js:21:42)
    at Object.<anonymous> (C:\Users\user\Desktop\arcgis-web-appbuilder-2.20\ArcGISWebAppBuilder\widget-developemnt\node_modules\esri-wab-build\app\build:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 224,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! widget-developemnt@1.0.0 build: `esri-wab-build C:/Users/user/Desktop/arcgis-web-appbuilder-2.20/ArcGISWebAppBuilder/server/apps/6`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the widget-developemnt@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-06-23T00_39_39_301Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-06-23T00_39_39_301Z-debug.log

```

**Comment by ryan-WORK** [comment]
ESRI has abandoned this
